-- require("auto-session").setup({
-- 	log_level = "info",
-- 	auto_session_enabled = true,
--     auto_restore_enabled = true,
--     auto_session_enable_last_session = true,
--     auto_save_enabled = true,
-- 	auto_session_root_dir = vim.fn.stdpath("data") .. "/sessions/",
--
-- 	pre_save_cmds = { "NvimTreeClose", "tabdo q" },
-- 	post_restore_cmds = { "NvimTreeOpen" },
--
-- 	-- Save window layout and folds
-- 	auto_session_allowed_dirs = nil,
-- })
--
-- vim.keymap.set("n", "<leader>ss", ":SessionSave<CR>", { desc = "Session Save" })
-- vim.keymap.set("n", "<leader>sr", ":SessionRestore<CR>", { desc = "Session Restore" })
--
